version: "3.8"

services:
  # api:
  #   build: .
  #   container_name: catalog-api
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app # Mount the source code for hot reload
  #     - air_tmp:/app/tmp # Avoid permission issues and keep container clean
  #   networks:
  #     - backend

  db:
    image: postgres:14
    container_name: catalog-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - backend

volumes:
  pgdata:
  # air_tmp: # Temporary directory for air builds
# networks:
#   backend:
#     driver: bridge
